Bump SentencePiece to 0.2.0
This version has binary wheels for arm64 macOS. 

Otherwise building SentencePiece wheel on Catalina is problematic due to them using implicit conversions disallowed in safemode libc++:

```
src/sentencepiece/sentencepiece_wrap.cxx:3658:38: error: no viable conversion from 'const vector<std::string>' to 'const vector<absl::string_view>
```